from enum import Enum


class EntityType(Enum):
    ACTOR = "ACTOR"
    ACTIVITY = "ACTIVITY"
    ACTIVITY_DATA = "ACTIVITY_DATA"
    FURTHER_SPECIFICATION = "FURTHER_SPECIFICATION"
    AND_GATEWAY = "AND_GATEWAY"
    XOR_GATEWAY = "XOR_GATEWAY"
    CONDITION_SPECIFICATION = "CONDITION_SPECIFICATION"
